##The website title
name: To Overcome
##Markdown processor
markdown: redcarpet
##syntax highlighter. change it to pygments
highlighter: pygments

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://www.parsonsmatt.org
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: Personal blog of Matthew Parsons
##Some frequently used keywords on your website
keywords: programming, music, haskell, weightlifting

##Some commonly used links
links:
  facebook: parsonsmatt
  twitter: mattoflambda
  email: hello@parsonsmatt.org
  github: parsonsmatt

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: me.png
##comment this if you want full width posts with no sidebar
# sidebar: on
