# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "To Overcome"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

gems:
    - jekyll-redirect-from
    - jekyll-paginate
    - jekyll-feed

paginate: 10
paginate_path: "page:num"
# Markdown
markdown: kramdown

kramdown:
    input: GFM
    hard_wrap: false
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
##syntax highlighter. change it to pygments
highlighter: rouge


# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name: "tutorials"
    href: "/tutorials"

  - name: "Twitter"
    href: "//www.twitter.com/mattoflambda"
  - name: "Github"
    href: "//www.github.com/parsonsmatt"
  - name: "Email"
    href: "mailto:hello@parsonsmatt.org"

##Some commonly used links
links:
  facebook: parsonsmatt
  twitter: mattoflambda
  email: hello@parsonsmatt.org
  github: parsonsmatt

##The website description (to be used in meta tags)
description: Personal blog of Matthew Parsons
##Some frequently used keywords on your website
keywords: programming, music, haskell, weightlifting

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
