# Site settings
title: To Overcome
email: hello@parsonsmatt.org
description: > # this means to ignore newlines until "baseurl:"
    Transhuman, feminist, and hopefully immortal optimization process. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.parsonsmatt.org" # the base hostname & protocol for your site
twitter_username: matt_view_ctrl
github_username:  parsonsmatt

# Build settings
markdown: redcarpet
